import discord

cmd_prefix = "!"

intents = discord.Intents.all()

client = discord.Client(intents=intents)
#beta test locations
gameplayChannels = ["grandtoronto", "downtown", "the-coast"]
#current build locations
fullGameplayChannels = [
"aether-beach",
"beach-houses",
"boardwalk",
"sailor-joes-fishing",
"slimes-mckenzi-tiki-bar",
"ab-transport-station",
"floating-rockys",
"the-arena",
"ms-whimsys-school-of-magic",
"sky-pier",
"floating-rockies-cannon",
"medium-boston",
"museum-of-neo-history",
"the-slime-pits",
"downtown",
"apartments",
"techno-ramen-hq",
"robo-supply-shop",
"techno-ramen-bar",
"food-trucks",
"mc-threads",
"central-station",
"uptown",
"town-houses",
"small-buisness-row",
"rooftap-gardens",
"the-arcade",
"want-a-pizza-me",
"uptown-transport",
"little-akihabara"
"abandoned-cyber-subway",
"pink-light-district",
"rowdy-rave",
"killer-kasino",
"radio-avenue",
"the-old-theater",
"neo-suburbia",
"the-suburbs",
"the-society-of-the-beige",
"judys-lemonade-stand",
"greys-dinner",
"veterans-hall",
"soy-labs",
"soy-laboratory",
"soy-labs-cannon",
"silicon-canyon",
"silicon-canyon-mines",
"clydes-cyber-armory",
"maggys-magitek-labs",
"silicon-canyon-cannon",
"neo-ohio-ridge",
"docs-bodega",
"cowabunga-subz",
"syries-smokez",
"heavenly-hills",
"garlic-clinic",
"old-radio-station",
"forest",
"church-of-the-fore-eyes",
"far-out-camp-grounds",
"anomaly-alley",
"national-park-association",
"the-rez",
"the-general-store",
"mount-monkey",
"monkey-mines",
"food-trucks-2",
"micro-business-way",
"asphalt-fields",
"quick-trip",
"best-decade-race-way",
"sewers",
"magic-walmart",
"food-court",
"clothes-aisle",
"weapons-aisle",
"groton-grocery",
"walmart-backroom",
]